# This file is machine-generated - editing it directly is not advised

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[InterProcessCommunication]]
deps = ["Dates", "Printf"]
git-tree-sha1 = "d64b1081541fe3a51f30154cbbd60529903e6e65"
uuid = "a7427343-1d15-5490-a218-bfcb7db836a2"
version = "0.1.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
